# Generated by Django 4.2.27 on 2026-01-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='core.unidadacademica'),
        ),
        migrations.AddField(
            model_name='materia',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.programaacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('unidad_academica', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('programa_academico', 'clave')},
        ),
    ]
