# Generated by Django 4.2.27 on 2026-01-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academico', '0002_initial'),
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='core.unidadacademica'),
        ),
        migrations.AddField(
            model_name='carga',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='carga',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='asignaciones.periodo'),
        ),
        migrations.AddField(
            model_name='carga',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='academico.profesor'),
        ),
        migrations.AddField(
            model_name='carga',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='core.programaacademico'),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='asignaciones.carga'),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('unidad_academica', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['profesor', 'periodo'], name='cargas_profeso_99eb36_idx'),
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['estado'], name='cargas_estado_0981b9_idx'),
        ),
    ]
